### ISSUE TITLE
Create a form processor capable of running on a vanilla community webapp 

### ISSUE THREAD

**Issue by rgange** [rgange/magnolia-recaptcha-v3#1]
Current for processor addRecaptcha.js needed updates to the webapp pom.

`
2021-01-18 19:14:36,618 ERROR templates.components.multistep.StartStepFormEngine: FormProcessor threw unexpected exception
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.json.JSONObject
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:421) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:73) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:514) ~[nashorn.jar:?]
	at javax.script.CompiledScript.eval(CompiledScript.java:92) ~[?:1.8.0_272]
	at info.magnolia.module.jsmodels.factory.JavascriptObjectFactory.evaluate(JavascriptObjectFactory.java:193) ~[magnolia-module-javascript-models-1.1.2-SNAPSHOT.jar:?]
	at info.magnolia.module.jsmodels.factory.JavascriptObjectFactory.createJavascriptObject(JavascriptObjectFactory.java:170) ~[magnolia-module-javascript-models-1.1.2-SNAPSHOT.jar:?]
	at info.magnolia.module.jsmodels.form.JavascriptFormProcessor.internalProcess(JavascriptFormProcessor.java:75) ~[magnolia-module-javascript-models-1.1.2-SNAPSHOT.jar:?]
	at info.magnolia.module.form.processors.AbstractFormProcessor.process(AbstractFormProcessor.java:68) ~[magnolia-form-2.7.1.jar:?]
	at info.magnolia.module.form.templates.components.AbstractFormEngine.executeProcessors(AbstractFormEngine.java:148) ~[magnolia-form-2.7.1.jar:?]
	at info.magnolia.module.form.engine.FormEngine.processSubmission(FormEngine.java:240) [magnolia-form-2.7.1.jar:?]
	at info.magnolia.module.form.engine.FormEngine.handleRequest(FormEngine.java:151) [magnolia-form-2.7.1.jar:?]
	at info.magnolia.module.form.templates.components.AbstractFormModel.execute(AbstractFormModel.java:101) [magnolia-form-2.7.1.jar:?]
	at info.magnolia.rendering.model.ModelExecutionFilter.doFilter(ModelExecutionFilter.java:146) [magnolia-rendering-6.2.5.jar:?]
        ...
        ...
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
`

The module https://mvnrepository.com/artifact/org.json/json is not included in the standard community bundle.

**Comment by rgange** [comment]
New script added: https://github.com/rgange/magnolia-recaptcha-v3/blob/master/templates/js/formProcessors/recaptcha.js
